### ISSUE TITLE
Not clear description of the project

### ISSUE THREAD

**Issue by ntodorov** [tobyqin/ccnet.datetimelabeller#1]
First thank you for the idea that I can create plugin as labeller!
By reading the project desctription it was not clear for me the you will use the datetime format ONLY for the build number (3rd quadrant).
I've spend some time looking the code before getting the proper understanding.

In any case good job!

I needed label in format yy.MM.dd.revision and I've used the core dateLabeller and yours as base for mine:
https://github.com/ntodorov/ccnet.formatedDateTimeLabeller.plugin

Thanks again,
Nik

**Comment by cicaday** [comment]
It is welcome to fork the project and do some customization, I believe your code can fit your best need :)
